cantantes = ['Breaking Benjamin', 'Linkin Park', 'Zoe', 'Skillet']
numeros = [10,6,5,3,2,1]
print(numeros)
print('*********')
numeros.sort()
print('*********')
print(numeros)
cantantes.append('War')
cantantes.insert(3, 'Skrillex')
print('*********')
print(cantantes)
print('*********')
cantantes.pop(2)
print(cantantes)
print('*********')
cantantes.remove('War')
print(cantantes)
print('*********')
print('Linkin Park' in cantantes)
print('*********')
cantantes.extend(numeros)
print(cantantes)